### PR TITLE
Omit keynotes from ELO vote

### PR DESCRIPTION
**Pull request by bplowry**
I haven't set this up and tested it locally, so I'd appreciate someone else having a look at it. 

I spent about 20 minutes clicking "Draw" in the front-end looking for a keynote to verify that `s.Format != "Keynote"` would actually get it, but they never came up and I don't have sufficient access in Azure to check the data itself.

### CODE REVIEW

**Comment by mzaatar** [comment]
Thanks, Ben, there is no clean way to eliminate the keynote at the moment as the `Keynote` tag is not being returned from Sessionize, instead, it returns as a `45 mins` session. 
Will send a ticket support to Sessionize to ask how could we do it

**Comment by mzaatar** [comment]
after contacting the support it seems that the Sessionize endpoint returns all tags and the issue might be in our sync service. Will send privately an API link to test

**Comment by bplowry** [comment]
Tried writing a test in `DDD.Sessionize.Tests` to see if it was a problem there but my fake thing came through with `Format: "Keynote"` so I'm not really sure where the problem is.

image

I added a hack to exclude the keynote based on ID which should work. It just means that if we get another keynote during the voting window we'll need to add its ID to the list, but since the sync won't be running it should be OK?

**Review by mzaatar — APPROVED** [review]
Hacky but remove it when we fix the tags in sessionize sync

**Pull request merged**
